name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Swift formatting
        run: make lint

      - name: Build project
        run: make build
